### ISSUE TITLE
Tests failing in clean virtualenv in Win10

### ISSUE THREAD

**Issue by tschier** [RaRe-Technologies/smart_open#129]
Hi project folks,

I've just set up a new environment (thinking of working on #43), have pulled latest master and run the tests and I'm getting two fail.

Win 10 1703
Python 3.6.2 64-bit

Made one modification to `requirements-test.txt` before installing those packages: changed `moto` to `moto<1`.

Ran tests with: `python -m unittest` in the base folder.

I'm seeing two failures. One to do with the gzip test where it's trying to remove a file that it thinks is still in use. I go and find the file and I can manually delete it no worries.
The other error is to invalid S3 credentials, on a test that is decorated with `@mock_s3`. So it looks like the mocking isn't working.

Just thought I'd check in to double-check that these are not some strange known-about things perhaps on latest python? One of the errors looks like #124. 

Two errors details:
```
ERROR: test_write_read_gz (smart_open.tests.test_smart_open.CompressionFormatTest)
Can write and read gzip?
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\schie\PycharmProjects\smart_open\smart_open\tests\test_smart_open.py", line 979, in test_write_read_gz
    self.write_read_assertion(test_file)
  File "C:\Users\schie\PycharmProjects\smart_open\smart_open\tests\test_smart_open.py", line 966, in write_read_assertion
    os.unlink(test_file)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\schie\\AppData\\Local\\Temp\\tmp9d11oz5u.gz'
```

and 

```
ERROR: test_s3_iter_bucket_moto (smart_open.tests.test_smart_open.S3IterBucketTest)
Does s3_iter_bucket work correctly?
----------------------------------------------------------------------
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "C:\Program Files\Python36\Lib\multiprocessing\pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "C:\Users\schie\PycharmProjects\smart_open\smart_open\smart_open_lib.py", line 953, in s3_iter_bucket_process_key_with_kwargs
    return s3_iter_bucket_process_key(**kwargs)
  File "C:\Users\schie\PycharmProjects\smart_open\smart_open\smart_open_lib.py", line 966, in s3_iter_bucket_process_key
    return key, key.get_contents_as_string()
  File "C:\Users\schie\PycharmProjects\smart_open_venv\lib\site-packages\boto\s3\key.py", line 1794, in get_contents_as_string
    response_headers=response_headers)
  File "C:\Users\schie\PycharmProjects\smart_open_venv\lib\site-packages\boto\s3\key.py", line 1662, in get_contents_to_file
    response_headers=response_headers)
  File "C:\Users\schie\PycharmProjects\smart_open_venv\lib\site-packages\boto\s3\key.py", line 1494, in get_file
    query_args=None)
  File "C:\Users\schie\PycharmProjects\smart_open_venv\lib\site-packages\boto\s3\key.py", line 1526, in _get_file_internal
    override_num_retries=override_num_retries)
  File "C:\Users\schie\PycharmProjects\smart_open_venv\lib\site-packages\boto\s3\key.py", line 355, in open
    override_num_retries=override_num_retries)
  File "C:\Users\schie\PycharmProjects\smart_open_venv\lib\site-packages\boto\s3\key.py", line 315, in open_read
    self.resp.reason, body)
boto.exception.S3ResponseError: S3ResponseError: 403 Forbidden
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>InvalidAccessKeyId</Code><Message>The AWS Access Key Id you provided does not exist in our records.</Message><AWSAccessKeyId>test-key</AWSAccessKeyId><RequestId>AEACFBA54E7C97D7</RequestId><HostId>kcAWz8TIE3yocyKdhVeQ4112jX9e79VaVJikd9svFjdNw3QwdoawsVKKmw6rtMwMFoQ7QVAg9EA=</HostId></Error>
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\schie\PycharmProjects\smart_open_venv\lib\site-packages\moto\core\models.py", line 71, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\schie\PycharmProjects\smart_open\smart_open\tests\test_smart_open.py", line 887, in test_s3_iter_bucket_moto
    for k, c in smart_open.s3_iter_bucket(mybucket):
  File "C:\Users\schie\PycharmProjects\smart_open\smart_open\smart_open_lib.py", line 1014, in s3_iter_bucket
    for key_no, (key, content) in enumerate(iterator):
  File "C:\Program Files\Python36\Lib\multiprocessing\pool.py", line 735, in next
    raise value
boto.exception.S3ResponseError: S3ResponseError: 403 Forbidden
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>InvalidAccessKeyId</Code><Message>The AWS Access Key Id you provided does not exist in our records.</Message><AWSAccessKeyId>test-key</AWSAccessKeyId><RequestId>AEACFBA54E7C97D7</RequestId><HostId>kcAWz8TIE3yocyKdhVeQ4112jX9e79VaVJikd9svFjdNw3QwdoawsVKKmw6rtMwMFoQ7QVAg9EA=</HostId></Error>
```

**Comment by menshikh-iv** [comment]
Thanks for report @tschier, I reproduced your problem.

**Comment by mpenkov** [comment]
[All the tests currently pass](https://github.com/RaRe-Technologies/smart_open/actions/runs/2214706863) on github actions, so closing.
