### ISSUE TITLE
Running smart_open with pypy(RPython) - BlockingIOError

### ISSUE THREAD

**Issue by CharushS** [RaRe-Technologies/smart_open#133]
I'm trying to run a gz read from s3 using the smart_open module, the code is working fine with CPython but while running with pypy , its throwing BlockingIOError

Traceback:

```
RPython traceback:

  File "pypy_interpreter.c", line 22173, in BuiltinCode_funcrun_obj

  File "pypy_module__io.c", line 5666, in W_BufferedRandom_readline_w

  File "implement_3.c", line 15554, in dispatcher_68

  File "pypy_module__io.c", line 24518, in W_BufferedRandom__raw_read

Traceback (most recent call last):

  File "file.py", line 893, in <module>

    test()

  File "file.py", line 850, in test

    for line in smart_open.smart_open("s3://bucket-name/"+str(key.name)):

  File "/home/user/pypy-5.8-linux_x86_64-portable/site-packages/smart_open/smart_open_lib.py", line 448, in __iter__

    for line in self.reader:

  File "/home/user/pypy-5.8-linux_x86_64-portable/site-packages/smart_open/gzipstreamfile.py", line 129, in readline

    result = super(GzipStreamFile, self).readline(*args, **kwargs)

SystemError: unexpected internal exception (please report a bug): <BlockingIOError object at 0x7f804120e820>; internal traceback was dumped to stderr
```

**Comment by menshikh-iv** [comment]
Hi @CharushS, we doesn't support pypy. You can try to report this bug to pypy developers.
