### ISSUE TITLE
Unable to iterate over gzipped object on S3

### ISSUE THREAD

**Issue by mpenkov** [RaRe-Technologies/smart_open#153]
Encountered while reproducing issue #152.

Given reproduce.py:

```python
import sys

from tqdm import tqdm
from smart_open import smart_open
for i, _ in enumerate(tqdm(smart_open(sys.argv[1], 'rb'))):
    if i > 1e5:
        break
```

This reproduces the bug:

```
(smartopen)sergeyich:issue152 misha$ git rev-parse --short HEAD
d10166c
(smartopen)sergeyich:issue152 misha$ time python reproduce.py s3://commoncrawl/crawl-002/2010/09/25/0/1285411480200_0.arc.gz
0it [00:00, ?it/s]Traceback (most recent call last):
  File "reproduce.py", line 5, in <module>
    for i, _ in enumerate(tqdm(smart_open(sys.argv[1], 'rb'))):
  File "/Users/misha/envs/smartopen/lib/python3.6/site-packages/tqdm/_tqdm.py", line 953, in __iter__
    for obj in iterable:
TypeError: 'closing' object is not iterable


real    0m3.131s
user    0m0.906s
sys     0m0.151s
```

**Comment by piskvorky** [comment]
@mpenkov is it a new 1.5.4 bug, or was it there in earlier versions? I remember gzip from S3 worked in the past.

**Comment by mpenkov** [comment]
@piskvorky I rewrote the S3 subsystem as part of Issue #91 .

The S3 issues emerging in 1.5.4 are a consequence of that recent rewrite.

**Comment by piskvorky** [comment]
OK, we need to improve the testing then.

@menshikh-iv can we do a bug fix release ASAP? This is critical.
