### ISSUE TITLE
Smart open does not work with S3 buckets containing dots

### ISSUE THREAD

**Issue by ziky90** [RaRe-Technologies/smart_open#26]
Smart open is not working with buckets that contains `.` in name such as `com.ziky90.project`.

Particularly I am getting an error log that looks as follows.

```
Traceback (most recent call last):
  File "/home/ubuntu/bucket_accessor/model_loader.py", line 70, in <module>
    model = TModel.load(model_path)
  File "/usr/local/lib/python2.7/dist-packages/gensim/utils.py", line 252, in load
    obj = unpickle(fname)
  File "/usr/local/lib/python2.7/dist-packages/gensim/utils.py", line 906, in unpickle
    with smart_open(fname) as f:
  File "/usr/local/lib/python2.7/dist-packages/smart_open/smart_open_lib.py", line 93, in smart_open
    return S3OpenRead(parsed_uri)
  File "/usr/local/lib/python2.7/dist-packages/smart_open/smart_open_lib.py", line 191, in __init__
    self.read_key = s3_connection.get_bucket(parsed_uri.bucket_id).lookup(parsed_uri.key_id)
  File "/usr/local/lib/python2.7/dist-packages/boto/s3/connection.py", line 502, in get_bucket
    return self.head_bucket(bucket_name, headers=headers)
  File "/usr/local/lib/python2.7/dist-packages/boto/s3/connection.py", line 521, in head_bucket
    response = self.make_request('HEAD', bucket_name, headers=headers)
  File "/usr/local/lib/python2.7/dist-packages/boto/s3/connection.py", line 664, in make_request
    retry_handler=retry_handler
  File "/usr/local/lib/python2.7/dist-packages/boto/connection.py", line 1071, in make_request
    retry_handler=retry_handler)
  File "/usr/local/lib/python2.7/dist-packages/boto/connection.py", line 943, in _mexe
    request.body, request.headers)
  File "/usr/lib/python2.7/httplib.py", line 1001, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1035, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 997, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 850, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 812, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 1212, in connect
    server_hostname=server_hostname)
  File "/usr/lib/python2.7/ssl.py", line 350, in wrap_socket
    _context=self)
  File "/usr/lib/python2.7/ssl.py", line 566, in __init__
    self.do_handshake()
  File "/usr/lib/python2.7/ssl.py", line 796, in do_handshake
    match_hostname(self.getpeercert(), self.server_hostname)
  File "/usr/lib/python2.7/ssl.py", line 269, in match_hostname
    % (hostname, ', '.join(map(repr, dnsnames))))
CertificateError: hostname 'com.ziky90.project.s3.amazonaws.com' doesn't match either of '*.s3.amazonaws.com', 's3.amazonaws.com'
```

**NOTE:** (I use smart_open from gensim)

It seems to me that the bug is related to https://github.com/boto/boto/issues/2836 and I am wondering if for example replacing boto by boto3  would help?

**Comment by piskvorky** [comment]
Thanks for reporting. Last time I looked, `boto3` was unfinished and had many issues.

But if it works better, we could (should) switch to boto3 of course. This will need careful testing (and updating all code) though, as the two libraries are not API-compatible IIRC.

**Comment by hobson** [comment]
Similar problem for me. Perhaps smart_open isn't being used recursively at the contained objects within models like `LsiModel` (`LsiModel.Projection` object is split into two pickles, and `smart_open` not being used to open them separately). I have no problem opening these pickles with `smart_open` using the exact URIs given in the warning message.

    ```python
    lsi = LsiModel.load(s3_uri('lsi_model_both_130K'))
    WARNING:root:failed to load projection from s3://XYZ@bucket-name/lsi_model_both_130K.projection: [Errno 2] No such file or directory: 's3://XYZ@bucket-name/lsi_model_both_130K.projection.u.npy'
    ```

**Comment by piskvorky** [comment]
That's right, the numpy object are loaded using numpy's native `load` operation, which doesn't support s3 or `smart_open`.

The easiest work-around is to store your object using pickle (a single file) and smart_open, avoiding the load/save that split the object into multiple files. Or pass `separately=[]` to `lsi.save()`, that should work too.

**Comment by hobson** [comment]
Perfect! Hadn't thought of the single-file workaround. Thanks!

**Comment by evdoks** [comment]
A solution to this issue would be to set `calling_format=ProtocolIndependentOrdinaryCallingFormat()` when calling `smart_open` and passing `calling_format` to `boto.connect_s3`. Additionally, you need to set `S3Connection.DefaultHost` to S3 endpoint with region name: e.g.,
`S3Connection.DefaultHost='s3-eu-west-1.amazonaws.com'`

**Comment by tmylk** [comment]
@evdoks Thanks for the troubleshooting. A PR and a test would be greatly appreciated.

**Comment by piskvorky** [comment]
@evdoks IIRC, in one of the recent PRs (merged already), we added passing parameters from smart_open directly through to S3.

Does that help with passing `calling_format` here?

**Comment by tmylk** [comment]
`calling_format` explicitly added in https://github.com/RaRe-Technologies/smart_open/pull/83

**Comment by mpenkov** [comment]
@ziky90 We replaced boto with boto3 in the S3 subsystem. Could you please check if the problem with dots in bucket names still occurs?

**Comment by menshikh-iv** [comment]
I close issue because it works fine with bucket name with dots (like `com.test-gensim.wow`) and current master fbc82cc04bf92e8c588c49c43ff5aff8234ea87d
