### ISSUE TITLE
Facing issue botocore.exceptions.ReadTimeoutError: Read timeout on endpoint URL: "None"

### ISSUE THREAD

**Issue by amitdhawan** [RaRe-Technologies/smart_open#312]
Hi,

Im facing a issue as below:-

```
Traceback (most recent call last):
  File "athena.py", line 242, in <module>
    for line in open('s3://' + s3_input_bucketname + '/' + s3_input_filepath, encoding='utf-8'):
  File "/usr/lib/python2.7/codecs.py", line 630, in next
    line = self.readline()
  File "/usr/lib/python2.7/codecs.py", line 545, in readline
    data = self.read(readsize, firstline=True)
  File "/usr/lib/python2.7/codecs.py", line 488, in read
    newdata = self.stream.read(size)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/smart_open/s3.py", line 253, in read
    self._fill_buffer(size)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/smart_open/s3.py", line 310, in _fill_buffer
    raw = self._raw_reader.read(size=self._buffer_size)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/smart_open/s3.py", line 178, in read
    binary = self._body.read(size)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/botocore/response.py", line 81, in read
    raise ReadTimeoutError(endpoint_url=e.url, error=e)
botocore.exceptions.ReadTimeoutError: Read timeout on endpoint URL: "None"
```

**Comment by mpenkov** [comment]
What smart_open version are you using?

Is this an intermittent issue? What happens if you retry reading?

**Comment by amitdhawan** [comment]
It was gz files i was trying to open for which i didn't mentioned the encoding format at open method call. Now i can see exactly which lines was causing issues in my csv.
