### ISSUE TITLE
compile issues with pyinstaller

### ISSUE THREAD

**Issue by douglasmccormickjr** [RaRe-Technologies/smart_open#345]
**Objective:** compile an app (using pyinstaller) that has the smart_open module.

**Issue:** I think the "VERSION" file isn't importing correctly.  Once the app compiles, if you start it in the command line, the error will trigger.

**Error:** Here's the error message I'm seeing when running the app

```
Traceback (most recent call last):
  File "splitter_129.py", line 26, in <module>
    import smart_open
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "c:\python360564\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "smart_open\__init__.py", line 39, in <module>
  File "smart_open\__init__.py", line 35, in _get_version
  File "smart_open\smart_open_lib.py", line 307, in open
  File "smart_open\smart_open_lib.py", line 512, in _shortcut_open
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\domccorm\\AppData\\Local\\Temp\\_MEI118122\\smart_open\\VERSION'
```

**Environment:** Windows 10, Python360564

It looks like someone else ran into this issue and posted within SO: https://stackoverflow.com/questions/57482672/filenotfounderror-errno-2-when-running-pyinstaller-executable

I'm not sure if the suggestions/answers on SO work -- I've been struggling and testing (trial and error) to see if I can fix it

Thanks so much,
-Doug Jr.

**Comment by piskvorky** [comment]
Hi Doug, check out https://github.com/RaRe-Technologies/smart_open/pull/344 . Can you try that and report whether it solves your issue?

**Comment by douglasmccormickjr** [comment]
Hi Piskvorky,

Thank you for the suggestion -- your approach solved it.  It would be great if the main smart_open library used that method of converting the VERSION file into version.py -- I'm thrilled that it's working now.

Have a great day,
-Doug Jr.

**Comment by shelley-chama** [comment]
I've been confronting with a same problem.
Could you tell me the commands you ran?
