### ISSUE TITLE
smart_open cannot be imported from within a zip file

### ISSUE THREAD

**Issue by eric-gravyty** [RaRe-Technologies/smart_open#347]
I'm trying to use smart_open from within an Apache Spark application by sending it to Spark wtihin a zip containing my application's third party dependencies. It works for all the other modules I'm importing, but the [`_get_version`](https://github.com/RaRe-Technologies/smart_open/blob/master/smart_open/__init__.py#L33-L36) function in `__init__.py` tries and fails to open the `VERSION` file.

```
Traceback (most recent call last):
  File "user_code.py", line 5, in <module>
    import smart_open
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/mnt/yarn/usercache/hadoop/appcache/application_1567622467027_0006/container_1567622467027_0006_01_000001/3rdparty.zip/smart_open/__init__.py", line 39, in <module>
  File "/mnt/yarn/usercache/hadoop/appcache/application_1567622467027_0006/container_1567622467027_0006_01_000001/3rdparty.zip/smart_open/__init__.py", line 35, in _get_version
  File "/mnt/yarn/usercache/hadoop/appcache/application_1567622467027_0006/container_1567622467027_0006_01_000001/3rdparty.zip/smart_open/smart_open_lib.py", line 307, in open
  File "/mnt/yarn/usercache/hadoop/appcache/application_1567622467027_0006/container_1567622467027_0006_01_000001/3rdparty.zip/smart_open/smart_open_lib.py", line 512, in _shortcut_open
NotADirectoryError: [Errno 20] Not a directory: '/mnt/yarn/usercache/hadoop/appcache/application_1567622467027_0006/container_1567622467027_0006_01_000001/3rdparty.zip/smart_open/VERSION'
```

storing the version in a .py file and importing it should solve this issue.

**Comment by piskvorky** [comment]
Solved by #344, I think. @mpenkov can we finish and merge that PR? It seems to bite quite a few people.
