### ISSUE TITLE
s3_iter_bucket for non default profile_name

### ISSUE THREAD

**Issue by dilzeem** [RaRe-Technologies/smart_open#366]
Hi, 

I am trying to use s3_iter_bucket with the non default profile name.

Currently when I try to do it, I get a 403 Error.

``` python

import boto3
boto3.setup_default_session(profile_name='non-default-profile', region_name='eu-west-1')


from smart_open import s3_iter_bucket, open

bucket = 'some_bucket'
prefix = 'some_prefix'
key = 'some_prefix' + 'some_key'


session = boto3.DEFAULT_SESSION
client = session.client('s3')

# this works
some_object = client.get_object(Bucket=bucket, Key=key)

# this works
same_object = open('s3://' +  bucket + '/' + key, transport_params=dict(session=session))

# get access denied when I try do iterate over this
s3bucket_objs = s3_iter_bucket(bucket, prefix=prefix)

```

**Comment by mpenkov** [comment]
Please show the full exception with the stack trace.

**Comment by piskvorky** [comment]
+ your `smart_open` version.

@mpenkov how about adding an issue template, similar to the one we have in gensim?

**Comment by dilzeem** [comment]
I am using smart_open version 1.8.4
Windows 10 OS


This is what I get when I do `next(s3bucket_objs)`:

```
RemoteTraceback                           Traceback (most recent call last)
RemoteTraceback: 
"""
Traceback (most recent call last):
  File "c:\Users\sivaharan.rajkumar\AppData\Local\Continuum\anaconda3\lib\multiprocessing\pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "c:\Users\sivaharan.rajkumar\AppData\Local\Continuum\anaconda3\lib\site-packages\smart_open\s3.py", line 660, in _download_key
    content_bytes = _download_fileobj(bucket, key_name)
  File "c:\Users\sivaharan.rajkumar\AppData\Local\Continuum\anaconda3\lib\site-packages\smart_open\s3.py", line 677, in _download_fileobj
    bucket.download_fileobj(key_name, buf)
  File "c:\Users\sivaharan.rajkumar\AppData\Local\Continuum\anaconda3\lib\site-packages\boto3\s3\inject.py", line 720, in bucket_download_fileobj
    Callback=Callback, Config=Config)
  File "c:\Users\sivaharan.rajkumar\AppData\Local\Continuum\anaconda3\lib\site-packages\boto3\s3\inject.py", line 678, in download_fileobj
    return future.result()
  File "c:\Users\sivaharan.rajkumar\AppData\Local\Continuum\anaconda3\lib\site-packages\s3transfer\futures.py", line 106, in result
    return self._coordinator.result()
  File "c:\Users\sivaharan.rajkumar\AppData\Local\Continuum\anaconda3\lib\site-packages\s3transfer\futures.py", line 265, in result
    raise self._exception
  File "c:\Users\sivaharan.rajkumar\AppData\Local\Continuum\anaconda3\lib\site-packages\s3transfer\tasks.py", line 255, in _main
    self._submit(transfer_future=transfer_future, **kwargs)
  File "c:\Users\sivaharan.rajkumar\AppData\Local\Continuum\anaconda3\lib\site-packages\s3transfer\download.py", line 345, in _submit
    **transfer_future.meta.call_args.extra_args
  File "c:\Users\sivaharan.rajkumar\AppData\Local\Continuum\anaconda3\lib\site-packages\botocore\client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "c:\Users\sivaharan.rajkumar\AppData\Local\Continuum\anaconda3\lib\site-packages\botocore\client.py", line 661, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (403) when calling the HeadObject operation: Forbidden
"""

The above exception was the direct cause of the following exception:

ClientError                               Traceback (most recent call last)
<ipython-input-2-47b8776c26c9> in <module>
----> 1 import codecs, os;__pyfile = codecs.open('''c:/Users/SIVAHA~1.RAJ/AppData/Local/Temp/pykFCUmf''', encoding='''utf-8''');__code = __pyfile.read().encode('''utf-8''');__pyfile.close();os.remove('''c:/Users/SIVAHA~1.RAJ/AppData/Local/Temp/pykFCUmf''');exec(compile(__code, '''c:/Users/sivaharan.rajkumar/GoogleDrive/projects/dee_debug/too_many_requests.py''', 'exec'));

c:/Users/sivaharan.rajkumar/GoogleDrive/projects/dee_debug/too_many_requests.py in <module>
     11 
     12 s3bucket_objs = s3_iter_bucket(bucket, prefix=prefix)
---> 13 next(s3bucket_objs)
     14 
     15 # session = boto3.DEFAULT_SESSION

c:\Users\sivaharan.rajkumar\AppData\Local\Continuum\anaconda3\lib\site-packages\smart_open\s3.py in iter_bucket(bucket_name, prefix, accept_key, key_limit, workers, retries)
    603     with _create_process_pool(processes=workers) as pool:
    604         result_iterator = pool.imap_unordered(download_key, key_iterator)
--> 605         for key_no, (key, content) in enumerate(result_iterator):
    606             if True or key_no % 1000 == 0:
    607                 logger.info(

c:\Users\sivaharan.rajkumar\AppData\Local\Continuum\anaconda3\lib\multiprocessing\pool.py in next(self, timeout)
    746         if success:
    747             return value
--> 748         raise value
    749 
    750     __next__ = next                    # XXX

ClientError: An error occurred (403) when calling the HeadObject operation: Forbidden
```

**Comment by mpenkov** [comment]
I cannot reproduce this with 1.9.0. Could you please try with that version? @dilzeem

**Comment by mpenkov** [comment]
We will release a new version soon that resolves the problem. For now, you can do this with the current master:

```python
smart_open.s3_iter_bucket(bucket_name, profile_name='non-default-profile', region_name='eu-west-1')
```
