### ISSUE TITLE
Not able to run tests

### ISSUE THREAD

**Issue by AndreaCrotti** [RaRe-Technologies/smart_open#55]
For some weird reason I can't seem to run tests with "python setup.py test", the error here below.
I'm getting this both with Python 2.7.10 and Python 3.4, any idea why?

```
    $> python setup.py test
    running test
    running egg_info
    writing requirements to smart_open.egg-info/requires.txt
    writing smart_open.egg-info/PKG-INFO
    writing top-level names to smart_open.egg-info/top_level.txt
    writing dependency_links to smart_open.egg-info/dependency_links.txt
    reading manifest file 'smart_open.egg-info/SOURCES.txt'
    writing manifest file 'smart_open.egg-info/SOURCES.txt'
    running build_ext
    Traceback (most recent call last):
      File "setup.py", line 66, in <module>
        'Topic :: Database :: Front-Ends',
      File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
        dist.run_commands()
      File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/home/andrea/.virtualenvs/smart_open/local/lib/python2.7/site-packages/setuptools/command/test.py", line 142, in run
        self.with_project_on_sys_path(self.run_tests)
      File "/home/andrea/.virtualenvs/smart_open/local/lib/python2.7/site-packages/setuptools/command/test.py", line 122, in with_project_on_sys_path
        func()
      File "/home/andrea/.virtualenvs/smart_open/local/lib/python2.7/site-packages/setuptools/command/test.py", line 163, in run_tests
        testRunner=self._resolve_as_ep(self.test_runner),
      File "/usr/lib/python2.7/unittest/main.py", line 94, in __init__
        self.parseArgs(argv)
      File "/usr/lib/python2.7/unittest/main.py", line 149, in parseArgs
        self.createTests()
      File "/usr/lib/python2.7/unittest/main.py", line 158, in createTests
        self.module)
      File "/usr/lib/python2.7/unittest/loader.py", line 130, in loadTestsFromNames
        suites = [self.loadTestsFromName(name, module) for name in names]
      File "/usr/lib/python2.7/unittest/loader.py", line 103, in loadTestsFromName
        return self.loadTestsFromModule(obj)
      File "/home/andrea/.virtualenvs/smart_open/local/lib/python2.7/site-packages/setuptools/command/test.py", line 37, in loadTestsFromModule
        tests.append(self.loadTestsFromName(submodule))
      File "/usr/lib/python2.7/unittest/loader.py", line 100, in loadTestsFromName
        parent, obj = obj, getattr(obj, part)
    AttributeError: 'module' object has no attribute 'test_smart_open'
```

If I use pytest even if I have installed all the dependencies I get

```
________________________________ ERROR collecting smart_open/tests/test_smart_open.py _________________________________
../../.local/lib/python2.7/site-packages/py/_path/local.py:650: in pyimport
    __import__(modname)
smart_open/__init__.py:1: in <module>
    from .smart_open_lib import *
smart_open/smart_open_lib.py:34: in <module>
    from boto.compat import BytesIO, urlsplit, six
E   ImportError: No module named boto.compat
=============================================== 1 error in 0.09 seconds =
```

**Comment by AndreaCrotti** [comment]
I finally managed to get it working, by doing the same thing as Travis is doing so installing these:

pip install httpretty==0.8.10 requests==2.8.1 mock moto responses

Not entirely sure why we get that error without these packages though, any idea?

**Comment by tmylk** [comment]
I don't know.

**Comment by piskvorky** [comment]
@tmylk can you reproduce this?

**Comment by piskvorky** [comment]
@tmylk can you reproduce this?

**Comment by AndreaCrotti** [comment]
Just tried again on a clean virtual environment and it doesn't happen anymore.
However some dependencies required for running tests are not declared anywhere except that in travis.yml and in the README..
Closing this for now

**Comment by tmylk** [comment]
@AndreaCrotti Thanks for highlighting this. Added `tests_require` to setup.py in https://github.com/RaRe-Technologies/smart_open/commit/a8b079b8be1e9559770dd0f701385b2361158e24

**Comment by bitonp** [comment]
Hiya.. trying to use in an AWS Lambda environment.. and keep getting the 'no module named boto' error. Its imported in smart_open_lib.py on line 39. Is this fixed in a different release? O do I need to carry around a version of boto as well?

**Comment by mpenkov** [comment]
@bitonp Yes, you need boto installed to use smart_open.

Please ask questions on the mailing list. Github tickets are for bugs and feature requests only (and this particular ticket isn't even relevant to your question).
