### ISSUE TITLE
Compressed file ended before the end-of-stream marker was reached

### ISSUE THREAD

**Issue by ivan-yankovyi** [RaRe-Technologies/smart_open#627]
I try to download files from third-party API and upload them to S3.

```
        with open(url, 'rb') as fin:
            with open(f"s3://{BUCKET}/{fpath}", 'wb') as fout:
                for line in fin:
                    fout.write(line)
```
Mostly smart_open works fine with other files but sometimes I'm getting an error

`ERROR:root:Compressed file ended before the end-of-stream marker was reached`

For example I'm getting an error with this file https://datasets.tardis.dev/v1/deribit/options_chain/2020/08/01/OPTIONS.csv.gz
but with browser I can download it without issues.

My log:

```
INFO:root:Opened https://datasets.tardis.dev/v1/deribit/options_chain/2020/08/01/OPTIONS.csv.gz
INFO:botocore.credentials:Found credentials in shared credentials file: ~/.aws/credentials
INFO:smart_open.s3:smart_open.s3.MultipartWriter('my-bucket', 'tardis/table_20200801.csv.gz'): uploading part_num: 1, 52456530 bytes (total 0.049GB)
INFO:smart_open.s3:smart_open.s3.MultipartWriter('my-bucket', 'tardis/table_20200801.csv.gz'): uploading part_num: 2, 52437910 bytes (total 0.098GB)
INFO:smart_open.s3:smart_open.s3.MultipartWriter('my-bucket', 'tardis/table_20200801.csv.gz'): uploading part_num: 3, 5235580 bytes (total 0.103GB)
ERROR:root:Compressed file ended before the end-of-stream marker was reached
```

**Comment by mpenkov** [comment]
So is the problem with the HTTP reading? In that case, is the S3 writing part not relevant to the example?

**Comment by ivan-yankovyi** [comment]
It seems the problem with S3 writing. It works when file uploaded locally.

**Comment by piskvorky** [comment]
Please post a full reproducible example, and a full stacktrace.

**Comment by ivan-yankovyi** [comment]
```
from smart_open import open


BUCKET = 'my-bucket'

def load_file(url, fpath):
    with open(url, 'rb') as fin:
        with open(f"s3://{BUCKET}/{fpath}", 'wb') as fout:
            for line in fin:
                fout.write(line)

load_file('https://datasets.tardis.dev/v1/deribit/options_chain/2020/08/01/OPTIONS.csv.gz', 'tardis//table_20200801.csv.gz')
```

```
Traceback (most recent call last):
  File "tardis_example.py", line 12, in <module>
    load_file('https://datasets.tardis.dev/v1/deribit/options_chain/2020/08/01/OPTIONS.csv.gz', 'tardis/table_20200801.csv.gz')
  File "tardis_example.py", line 9, in load_file
    for line in fin:
  File "/usr/lib/python3.8/gzip.py", line 390, in readline
    return self._buffer.readline(size)
  File "/usr/lib/python3.8/_compression.py", line 68, in readinto
    data = self.read(len(byte_view))
  File "/usr/lib/python3.8/gzip.py", line 498, in read
    raise EOFError("Compressed file ended before the "
EOFError: Compressed file ended before the end-of-stream marker was reached
```

**Comment by mpenkov** [comment]
These lines suggest the problem is with reading, not writing:

```
  File "/usr/lib/python3.8/gzip.py", line 390, in readline
    return self._buffer.readline(size)
  File "/usr/lib/python3.8/_compression.py", line 68, in readinto
    data = self.read(len(byte_view))
  File "/usr/lib/python3.8/gzip.py", line 498, in read
    raise EOFError("Compressed file ended before the "
EOFError: Compressed file ended before the end-of-stream marker was reached
```

Are you able to step through with a debugger?

**Comment by ivan-yankovyi** [comment]
What should I do with a debugger? I am confused by the fact that locally I can write without errors, but when writing to s3 I get this error.

**Comment by mpenkov** [comment]
Yes, this is very strange.

It will require some investigation, but I don't know when I'll get around to it.

If you have the resources to look at this yourself, then here is what I would do if I were investigating this. First, I would try to narrow down the sample you provided even further (again, the error appears to be with reading, so the writing part may be a red herring). I would look at what bytes are actually being read by smart_open over the wire, and compare them to the contents of the local copy of the file.

The debugger would help you with that last part (examining the bytes read). You could also do the same thing with print statements.
