### ISSUE TITLE
Using threads with smartopen raises boto3 KeyError exception

### ISSUE THREAD

**Issue by stolam** [RaRe-Technologies/smart_open#647]
#### Problem description
When trying to load files from S3 in parallel using `ThreadPoolExecutor`, there is a high chance an exception will be thrown from boto3. All files should be read by `smart-open` correctly. 
I noticed, it was OK in versions prior to 5.x, where you changed the way you use `boto3` under the hood.

This is link to an existing boto3 issue
https://github.com/boto/boto3/issues/1592

There is a workaround using sessions, but I think it can't be done easily with the `smart-open` 5.2,
therefore I will continue to use older versions.

#### Steps/code to reproduce the problem

upload any text file to S3 to some `S3_PATH_TO_A_FILE`
contents tested, e.g.:
"this is a tiny file in S3"

Then try to load the file multiple times in threads:
```
from concurrent.futures import ThreadPoolExecutor
from smart_open import smart_open

path = "S3_PATH_TO_A_FILE"
def func(p):
    with smart_open(p) as f:
        for _ in f:
            pass


with ThreadPoolExecutor(max_workers=8) as executor:
    list(executor.map(func, [path] * 10))
```
For the sake of simplicity, the snippet tries to read a single file, but it also crashes with distinct unique files.
Decreasing the number of workers increases the chance of avoiding the exception.

Stacktrace:
```
Traceback (most recent call last):
  File "/home/stola/Projects/robobrain/smart_issue.py", line 14, in <module>
    list(executor.map(func, [path] * 10))
  File "/home/stola/anaconda3/envs/robo/lib/python3.7/concurrent/futures/_base.py", line 598, in result_iterator
    yield fs.pop().result()
  File "/home/stola/anaconda3/envs/robo/lib/python3.7/concurrent/futures/_base.py", line 428, in result
    return self.__get_result()
  File "/home/stola/anaconda3/envs/robo/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/home/stola/anaconda3/envs/robo/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/stola/Projects/robobrain/smart_issue.py", line 8, in func
    with smart_open(p) as f:
  File "/home/stola/anaconda3/envs/robo/lib/python3.7/site-packages/smart_open/smart_open_lib.py", line 498, in smart_open
    return open(**locals())
  File "/home/stola/anaconda3/envs/robo/lib/python3.7/site-packages/smart_open/smart_open_lib.py", line 235, in open
    binary = _open_binary_stream(uri, binary_mode, transport_params)
  File "/home/stola/anaconda3/envs/robo/lib/python3.7/site-packages/smart_open/smart_open_lib.py", line 398, in _open_binary_stream
    fobj = submodule.open_uri(uri, mode, transport_params)
  File "/home/stola/anaconda3/envs/robo/lib/python3.7/site-packages/smart_open/s3.py", line 224, in open_uri
    return open(parsed_uri['bucket_id'], parsed_uri['key_id'], mode, **kwargs)
  File "/home/stola/anaconda3/envs/robo/lib/python3.7/site-packages/smart_open/s3.py", line 298, in open
    client_kwargs=client_kwargs,
  File "/home/stola/anaconda3/envs/robo/lib/python3.7/site-packages/smart_open/s3.py", line 555, in __init__
    _initialize_boto3(self, client, client_kwargs, bucket, key)
  File "/home/stola/anaconda3/envs/robo/lib/python3.7/site-packages/smart_open/s3.py", line 528, in _initialize_boto3
    client = boto3.client('s3', **init_kwargs)
  File "/home/stola/anaconda3/envs/robo/lib/python3.7/site-packages/boto3/__init__.py", line 93, in client
    return _get_default_session().client(*args, **kwargs)
  File "/home/stola/anaconda3/envs/robo/lib/python3.7/site-packages/boto3/session.py", line 263, in client
    aws_session_token=aws_session_token, config=config)
  File "/home/stola/anaconda3/envs/robo/lib/python3.7/site-packages/botocore/session.py", line 839, in create_client
    credentials = self.get_credentials()
  File "/home/stola/anaconda3/envs/robo/lib/python3.7/site-packages/botocore/session.py", line 442, in get_credentials
    'credential_provider').load_credentials()
  File "/home/stola/anaconda3/envs/robo/lib/python3.7/site-packages/botocore/session.py", line 941, in get_component
    del self._deferred[name]
KeyError: 'credential_provider'

Process finished with exit code 1

```

#### Versions
Linux-4.15.0-154-generic-x86_64-with-debian-buster-sid
Python 3.7.11 (default, Jul 27 2021, 14:32:16) 
[GCC 7.5.0]
smart_open 5.2.1
boto 2.49.0
boto3 1.18.27
botocore 1.21.27

#### Checklist

Before you create the issue, please make sure you have:

- [x] Described the problem clearly
- [x] Provided a minimal reproducible example, including any required data
- [x] Provided the version numbers of the relevant software

**Comment by mpenkov** [comment]
Have you tried creating one client per thread and then passing that to smart_open as a transport parameter?

https://github.com/RaRe-Technologies/smart_open/blob/develop/howto.md#how-to-read-from-s3-efficiently

Boto3 recommend you manage your own clients/sessions when working with multiple threads and processes.

The older version works because it opened a new session automatically for each file. In highly concurrent environments, this can cause out-of-memory conditions, because the sessions accumulate.

**Comment by stolam** [comment]
Thank you for the swift reply and the suggestion.
Changing `smart_open->open` and supplying the client through the parameters helped.
Thank you!
