### ISSUE TITLE
_MULTIPROCESSING support test fails on Lambda

### ISSUE THREAD

**Issue by ronkorving** [RaRe-Technologies/smart_open#672]
#### Problem description

When running `smart_open.s3.iter_bucket`, it fails on AWS Lambda, because the error that is thrown is:

```
[ERROR] OSError: [Errno 38] Function not implemented
```

The code seems to only catch `ImportError`, and not `OSError`, so it slips through and blows up.

```
creating multiprocessing pool with 16 workers
[ERROR] OSError: [Errno 38] Function not implemented
Traceback (most recent call last):
  File "/var/task/lambdas/mycode.py", line 83, in <listcomp>
    return [
  File "/var/task/smart_open/s3.py", line 1190, in iter_bucket
    with smart_open.concurrency.create_pool(processes=workers) as pool:
  File "/var/lang/lib/python3.9/contextlib.py", line 119, in __enter__
    return next(self.gen)
  File "/var/task/smart_open/concurrency.py", line 68, in create_pool
    pool = multiprocessing.pool.Pool(processes=processes)
  File "/var/lang/lib/python3.9/multiprocessing/pool.py", line 191, in __init__
    self._setup_queues()
  File "/var/lang/lib/python3.9/multiprocessing/pool.py", line 343, in _setup_queues
    self._inqueue = self._ctx.SimpleQueue()
  File "/var/lang/lib/python3.9/multiprocessing/context.py", line 113, in SimpleQueue
    return SimpleQueue(ctx=self.get_context())
  File "/var/lang/lib/python3.9/multiprocessing/queues.py", line 342, in __init__
    self._rlock = ctx.Lock()
  File "/var/lang/lib/python3.9/multiprocessing/context.py", line 68, in Lock
    return Lock(ctx=self.get_context())
  File "/var/lang/lib/python3.9/multiprocessing/synchronize.py", line 162, in __init__
    SemLock.__init__(self, SEMAPHORE, 1, 1, ctx=ctx)
  File "/var/lang/lib/python3.9/multiprocessing/synchronize.py", line 57, in __init__
    sl = self._semlock = _multiprocessing.SemLock(
```

#### Steps/code to reproduce the problem

Literally just call that function on AWS Lambda.

#### Versions

```python
import platform, sys, smart_open
print(platform.platform())
print("Python", sys.version)
print("smart_open", smart_open.__version__)
```

from the Lambda prints:

* Linux-4.14.246-198.474.amzn2.x86_64-x86_64-with-glibc2.26
* Python 3.9.8 (main, Nov 17 2021, 10:48:43)
* [GCC 7.3.1 20180712 (Red Hat 7.3.1-13)]
* smart_open 5.2.1

#### Checklist

Before you create the issue, please make sure you have:

- [x] Described the problem clearly
- [x] Provided a minimal reproducible example, including any required data
- [x] Provided the version numbers of the relevant software

**Comment by ddelange** [comment]
PR welcome!
